### ISSUE TITLE
history-page-create

### ISSUE THREAD

**Issue by DoHyeongKwonn** [Fan-Tion/Front-End#12]
**Is your feature request related to a problem? Please describe.**
거래 내역 페이지와 예치금 입출금 내역 페이지를 생성합니다.

**Describe the solution you'd like**
사용자가 자신의 거래 내역과 예치금 입출금 내역을 확인할 수 있는 페이지의 디자인을 임시로 생성합니다.

**Describe alternatives you've considered**

**Additional context**

**Comment by FioreFlower** [comment]
5일째 업데이트가 없는데 진행상황 업데이트 부탁드려요.
