### ISSUE TITLE
mock-handler-correction

### ISSUE THREAD

**Issue by Min-byeonghyun** [Fan-Tion/Front-End#38]
**Describe the bug**
회원가입, 로그인, 비밀번호 변경 Mocks / handlers.ts 에서 Type 오류가 발생합니다.

**To Reproduce**

**Expected behavior**
회원가입, 로그인, 비밀번호 변경 Mock 핸들러가 TypeScript 오류 없이 동작해야 합니다.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by FioreFlower** [comment]
#39 이슈와 중복되는 내용이므로 #39에서 이어서 팔로우업 해주세요.
중복 이슈는 클로즈 하겠습니다.
